// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemServiceMonitor.Core.Data;

#nullable disable

namespace SystemServiceMonitor.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("SystemServiceMonitor.Core.Models.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRepairEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependencyIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeployedCommitHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("DesiredState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthcheckCommand")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresElevation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestartCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopCommand")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("WslDistroName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
